local GLOBALEVENT_BEGIN = 100;

GLOBALEVENT = 
{
    GE_GENERATE_GAMESCENE		= GLOBALEVENT_BEGIN;
	GE_ITEM_UPDATE				= GLOBALEVENT_BEGIN + 1;
	GE_KILL_MONSTER				= GLOBALEVENT_BEGIN + 2;
    GE_LOGIN_GAME               = GLOBALEVENT_BEGIN + 3;
	GE_SWITCH					= GLOBALEVENT_BEGIN + 4,
};