local _MSG_GENERAL = 1000;

NMSG_Type = 
{
	_MSG_USERINFO					= _MSG_GENERAL + 8,
	_MSG_USERINFO_UPDATE			= _MSG_GENERAL + 40,
	TASK_NPC_MSG					= _MSG_GENERAL + 22,
	_MSG_PETINFO					= _MSG_GENERAL + 39,
	_MSG_PETINFO_UPDATE				= _MSG_GENERAL + 3000,
	_MSG_TASK_ACTION				= _MSG_GENERAL + 1097,
	_MSG_TASK_DATA_ACTION			= _MSG_GENERAL + 1098,
	_MSG_TASK_NPC_ACTION			= _MSG_GENERAL + 1099,
	_MSG_ITEM_INFO					= _MSG_GENERAL + 16,
	_MSG_ITEM_ACTION				= _MSG_GENERAL + 17,
	
	_MSG_MATRIX_LIST				= _MSG_GENERAL + 3500,
	_MSG_MATRIX_ADDED				= _MSG_GENERAL + 3501,
	_MSG_MATRIX_UPGRADED			= _MSG_GENERAL + 3502,
	_MSG_MATRIX_COOLDOWN			= _MSG_GENERAL + 3503,
	_MSG_MATRIX_STATION				= _MSG_GENERAL + 3504,
	_MSG_MATRIX_STATION_OPEN		= _MSG_GENERAL + 3505,
	_MSG_ATTACK_LIST				= _MSG_GENERAL + 3510,
	_MSG_ATTACK_ADDED				= _MSG_GENERAL + 3511,
	_MSG_ATTACK_UPGRADED			= _MSG_GENERAL + 3512,
	_MSG_ATTACK_COOLDOWN			= _MSG_GENERAL + 3513,
	_MSG_REALIZE_MERGE				= _MSG_GENERAL + 3516,
	_MSG_REALIZE_OPEN				= _MSG_GENERAL + 3517,
	_MSG_REALIZE_BUY				= _MSG_GENERAL + 3518,
	_MSG_REALIZE_LIST				= _MSG_GENERAL + 3529,
	_MSG_REALIZE_SALE				= _MSG_GENERAL + 3530,
	_MSG_REALIZE_PICKUP_ALL			= _MSG_GENERAL + 3531,
	_MSG_REALIZE_SALE_ALL			= _MSG_GENERAL + 3532,
	_MSG_REALIZE_MERGE_ALL			= _MSG_GENERAL + 3533,
	_MSG_REALIZE_BUY_ALL			= _MSG_GENERAL + 3534,
	_MSG_ROLE_TRAIN_GET				= _MSG_GENERAL + 3506,
	_MSG_ROLE_TRAIN_TRAIN			= _MSG_GENERAL + 3507,
	_MSG_ROLE_TRAIN_COMMIT			= _MSG_GENERAL + 3508,
	_MSG_EQUIP_UPD_CD_LST			= _MSG_GENERAL + 3522,
	_MSG_EQUIP_UPD_CD_CLEAN			= _MSG_GENERAL + 3523,
	_MSG_EQUIP_UPD_CD_QUE_ADD		= _MSG_GENERAL + 3524,

	_MSG_PET_SHOP_ACTION			= _MSG_GENERAL + 3001,
	_MSG_ITEM_ATTRIB				= _MSG_GENERAL + 45,
	_MSG_PET_IMPART					= _MSG_GENERAL + 3005,
	
	_MSG_AFFIX_BOSS_NML_OPEN	    = _MSG_GENERAL + 3540,
	_MSG_AFFIX_BOSS_NML_ENTER		= _MSG_GENERAL + 3541,
	_MSG_AFFIX_BOSS_NML_CLEARUP		= _MSG_GENERAL + 3542,
	_MSG_AFFIX_BOSS_NML_CANCEL      = _MSG_GENERAL + 3543,
	_MSG_AFFIX_BOSS_NML_FINISH		= _MSG_GENERAL + 3544,
	_MSG_AFFIX_BOSS_NML_LEAVE		= _MSG_GENERAL + 3545,
	_MSG_AFFIX_BOSS_NML_RESET		= _MSG_GENERAL + 3550,

	_MSG_NPC						= _MSG_GENERAL+1031,
	
	_MSG_BOSS_BATTLE_INFO			= _MSG_GENERAL + 3007,
	_MSG_BOSS_SELF_INFO				= _MSG_GENERAL + 3009,
	_MSG_LIMIT						= _MSG_GENERAL+1508,	-- 格子上限
	
	_MSG_BOSS_BATTLE				= _MSG_GENERAL + 3006,
	
	_MSG_SPORTS						= _MSG_GENERAL + 3002,
	_MSG_SPORTS_INFO				= _MSG_GENERAL + 3003,
	_MSG_SPORTS_FRONT_INFO			= _MSG_GENERAL + 3004,
	_MSG_SPORTS_WATCH_BATTLE		= _MSG_GENERAL + 3010,
	_MSG_DAILY_ACTIVITY_LIST		= _MSG_GENERAL + 3557,
	_MSG_START_BOSS_BATTLE			= _MSG_GENERAL + 3558,
	
	_MSG_START_FORMULA_DATA			= _MSG_GENERAL + 1505,
    --Login Message
    MB_LOGINSYSTEM_MOBILE_SERVER_NOTIFY = 60000,
    MB_LOGINSYSTEM_CREATE_NEWBIE        = 60018,
    _MSG_NOTIFY_CLIENT              = _MSG_GENERAL+1028,
	_MSG_QUIT_BOSS_BATTLE			= _MSG_GENERAL + 3559,
	
	_MSG_GIFTPACK_LIST				= _MSG_GENERAL + 3520,
	_MSG_GET_GIFTPACK				= _MSG_GENERAL + 3519,
};