--属性UI
DoFile("Player/PlayerFunc.lua");
DoFile("Player/PlayerEnum.lua");
DoFile("Player/PlayerUIAttr.lua");
DoFile("Player/PlayerUIBackBag.lua");
DoFile("Player/PlayerUICompose.lua");
DoFile("Player/PlayerUIPill.lua");
DoFile("Player/PlayerVip.lua");
DoFile("Player/PlayerNimbusUI.lua");