/*
 *  NDMsgDefine.h
 *  DragonDrive
 *
 *  Created by jhzheng on 10-12-27.
 *  Copyright 2010 __MyCompanyName__. All rights reserved.
 *
 */

#ifndef _ND_MSG_DEFINE_H_
#define _ND_MSG_DEFINE_H_

typedef unsigned short MSGID;

enum ND_MSG_CODE
{
	_POSITION_MAPCHANGE = 8, 
	_POSITION_TRANS_FLY = 27,
	_WORD_MAPCHANGE = 28,
	
	// -------------------- TXT style define --------------------------
	_TXT_NORMAL			=0,
	_TXT_SCROLL			=0x0001,
	_TXT_FLASH				=0x0002,
	_TXT_BLAST				=0x0008,
	
	// -------------------- TXT attribute define --------------------------
	_TXTATR_NORMAL		    =0,
	_TXTATR_PRIVATE	    =_TXTATR_NORMAL+1,	// 私聊
	_TXTATR_ACTION		    =_TXTATR_NORMAL+2,	// 动作
	_TXTATR_TEAM		    =_TXTATR_NORMAL+3,	// 队伍
	_TXTATR_SYNDICATE	    =_TXTATR_NORMAL+4,	// 帮派
	_TXTATR_SYSTEM		    =_TXTATR_NORMAL+5,	// 系统
	_TXTATR_FAMILY		    =_TXTATR_NORMAL+6,	// 家庭
	_TXTATR_TALK		    =_TXTATR_NORMAL+7,	// 交谈
	_TXTATR_YELP 		    =_TXTATR_NORMAL+8,	// 叫喊
	_TXTATR_FRIEND 	    =_TXTATR_NORMAL+9,	// 朋友
	_TXTATR_GLOBAL 	    =_TXTATR_NORMAL+10,	// 千里传音
	_TXTATR_GM 		    =_TXTATR_NORMAL+11,	// GM频道
	_TXTATR_WHISPER 	    =_TXTATR_NORMAL+12,	// 耳语
	_TXTATR_GHOST	 	    =_TXTATR_NORMAL+13,	// 幽灵
	_TXTATR_SERVE		    =_TXTATR_NORMAL+14, // 世界
	_TXTATR_MATE		    =_TXTATR_NORMAL+15, // 夫妻
	_TXTATR_MENTOR		    =_TXTATR_NORMAL+16, // 师门
	_TXTATR_SYSTEM_DIALOG	=_TXTATR_NORMAL+17,	// 系统对话框
	_TXTATR_CHAT		    =_TXTATR_NORMAL+18,	// 独立聊天
	_TXTATR_MAP			=_TXTATR_NORMAL+19, // 地图
	_TXTATR_SYSTEM_EMPHASIS=_TXTATR_NORMAL+20,	// 重要系统提示
	_TXTATR_SYSTEM_SPECIAL =_TXTATR_NORMAL+21,	// 特殊增值服务消息
	
	_TXTATR_REGISTER	    =_TXTATR_NORMAL+100,
	_TXTATR_ENTRANCE	    =_TXTATR_NORMAL+101,
	_TXTATR_SHOP		    =_TXTATR_NORMAL+102,
	_TXTATR_PETTALK	    =_TXTATR_NORMAL+103,
	_TXTATR_CRYOUT		    =_TXTATR_NORMAL+104,
	_TXTATR_WEBPAGE	    =_TXTATR_NORMAL+105,
	_TXTATR_NEWMESSAGE	    =_TXTATR_NORMAL+106,
	_TXTATR_TASK		    =_TXTATR_NORMAL+107,
	_TXTATR_QUIZQUESTION   =_TXTATR_NORMAL+108,
	_TXTATR_QUIZANSWER	    =_TXTATR_NORMAL+109,
	
	_TXTATR_LEAVEWORD	    =_TXTATR_NORMAL+110, // 留言系统
	_TXTATR_SYNANNOUNCE    =_TXTATR_NORMAL+111, // 帮派公告
	_TXTATR_MESSAGEBOX	    =_TXTATR_NORMAL+112, // 弹出对话框
	
	_TXTATR_MSG_TRADE	    =_TXTATR_NORMAL+201, // 交易留言板
	_TXTATR_MSG_FRIEND	    =_TXTATR_NORMAL+202, // 交友留言板
	_TXTATR_MSG_TEAM	    =_TXTATR_NORMAL+203, // 组队留言板
	_TXTATR_MSG_SYN	    =_TXTATR_NORMAL+204, // 帮派留言板
	_TXTATR_MSG_OTHER	    =_TXTATR_NORMAL+205, // 其它留言板
	_TXTATR_PIGEON		    =_TXTATR_NORMAL+500, // 魔法飞鸽
	
	
	_MSG_NONE				=0,
	// -------------------- internal msg type define --------------------------
	_MSG_INTERNAL			=100,
	_MSG_LOG				=_MSG_INTERNAL+1,		// LOGServe
	
	_MSG_LOAD				=_MSG_INTERNAL+10,		// DBServe
	
	_MSG_CHECKIN			=_MSG_INTERNAL+20,		// LoginServe
	_MSG_CHECKOUT			=_MSG_INTERNAL+21,		// LoginServe
	
	_MSG_NOTIFY			=_MSG_INTERNAL+30,		// GameServe
	_MSG_NEWBIE			=_MSG_INTERNAL+31,		// GameServe
	_MSG_LOGIN				=_MSG_INTERNAL+32,		// GameServe
	_MSG_LOGOUT			=_MSG_INTERNAL+33,		// GameServe
	_MSG_HOLDING			=_MSG_INTERNAL+34,		// GameServe
	_MSG_RECONNECT			=_MSG_INTERNAL+35,		// GameServe
	_MSG_LOGINOVER			=_MSG_INTERNAL+36,		// GameServe
	_MSG_WALLOW			=_MSG_INTERNAL+37,		// 防止沉迷
	_MSG_MULTICASTMSG		=_MSG_INTERNAL+38,		// 组播消息
	_MSG_GMCOMMAND			=_MSG_INTERNAL+39,		// GM命令
	
	// -------------------- msg type define --------------------------
	_MSG_GENERAL			=1000,
	_MSG_ERROR				=_MSG_GENERAL+1,
	_MSG_REPLAY			=_MSG_GENERAL+2,		// 从客户端返回的消息
	_MSG_TALK				=_MSG_GENERAL+4,
	_MSG_WALK_EX			=_MSG_GENERAL+5,
	_MSG_EMOTION			=_MSG_GENERAL+6,
	_MSG_USERINFO			=_MSG_GENERAL+8,
	_MSG_ATTACK			=_MSG_GENERAL+9,
	_MSG_STEAL				=_MSG_GENERAL+10,
	_MSG_SCHOOL			=_MSG_GENERAL+11,
	_MSG_EXCHANGE			=_MSG_GENERAL+12,
	_MSG_DIE				=_MSG_GENERAL+13,
	_MSG_REBORN			=_MSG_GENERAL+14,
	_MSG_REGISTER			=_MSG_GENERAL+15,
	_MSG_ITEMINFO			=_MSG_GENERAL+16,
	_MSG_ITEM				=_MSG_GENERAL+17,
	_MSG_DIR				=_MSG_GENERAL+18,
	_MSG_ACCIDENT			=_MSG_GENERAL+19,
	_MSG_TICK				=_MSG_GENERAL+20,
	_MSG_DIALOG			=_MSG_GENERAL+22,
	_MSG_SHOP				=_MSG_GENERAL+23,
	_MSG_ITEM_DEL			=_MSG_GENERAL+25,
	
	_MSG_MARRIAGE			=_MSG_GENERAL+30,
	_MSG_PLAYER			=_MSG_GENERAL+32,
	_MSG_PET				=_MSG_GENERAL+33,
	_MSG_BEHEAL			=_MSG_GENERAL+36,
	_MSG_NAME				=_MSG_GENERAL+37,
	_MSG_WEATHER			=_MSG_GENERAL+38,
	_MSG_PETINFO			=_MSG_GENERAL+39,
	
	_MSG_USERATTRIB		=_MSG_GENERAL+40,
	_MSG_POINTALLOT		=_MSG_GENERAL+41,
	_MSG_PETCOLLECTION		=_MSG_GENERAL+42,
	_MSG_SKILLINFO			=_MSG_GENERAL+43,
	_MSG_PLAYER_EXT		=_MSG_GENERAL+44,
	_MSG_ITEM_ATTRIB		=_MSG_GENERAL+45,
	_MSG_PLAYER_RECON		=_MSG_GENERAL+46,
	_MSG_PLAYER_EXT_RECON	=_MSG_GENERAL+47,
	
	_MSG_ROLE				=_MSG_GENERAL+50,
	_MSG_ACCOUNT			=_MSG_GENERAL+51,
	_MSG_CONNECT			=_MSG_GENERAL+52,
	_MSG_DELETEROLE		=_MSG_GENERAL+53,
	_MSG_BARACCOUNT		=_MSG_GENERAL+54,
	_MSG_SKILL				=_MSG_GENERAL+55,
	_MSG_TRADE				=_MSG_GENERAL+56,
	_MSG_CONJURE			=_MSG_GENERAL+57,
	_MSG_CREATE_ROLE		=_MSG_GENERAL+58,
	_MSG_POSITION			=_MSG_GENERAL+77,
	_MSG_ROOM				=_MSG_GENERAL+78,
	_MSG_DISCONNECT		=_MSG_GENERAL+98,
	_MSG_ACCOUNT_EX		=_MSG_GENERAL+99,
	
	_MSG_GM				=_MSG_GENERAL+100,
	
	_MSG_WALK				=_MSG_GENERAL+108,
	_MSG_KICK_BACK			=_MSG_GENERAL+109,
	
	_MSG_PASSWORD_SHIELD	= _MSG_GENERAL + 161,
	
	_MSG_QUERYFEE			=_MSG_GENERAL+201,
	_MSG_FEE_EX			=_MSG_GENERAL+202,
	
	_MSG_REGENERATOR		=_MSG_GENERAL+300,
	_MSG_GENERATOR			=_MSG_GENERAL+301,
	_MSG_ACTION			=_MSG_GENERAL+302,
	
	_MSG_SENDLETTER		=_MSG_GENERAL+400,
	_MSG_LETTER			=_MSG_GENERAL+401,
	_MSG_LETTER_INFO		=_MSG_GENERAL+402,
	_MSG_LETTER_REQUEST	=_MSG_GENERAL+403,
	
	_MSG_BATTLEACT			=_MSG_GENERAL+1000,
	_MSG_NORMALACT			=_MSG_GENERAL+1001,
	_MSG_SPECIALACT		=_MSG_GENERAL+1002,
	_MSG_PETACT			=_MSG_GENERAL+1003,
	_MSG_ITEMACT			=_MSG_GENERAL+1004,
	_MSG_BATTLE			=_MSG_GENERAL+1005,
	_MSG_OPPONENT			=_MSG_GENERAL+1007,
	_MSG_FRIEND			=_MSG_GENERAL+1008,
	
	//_MSG_BATTLERESULT		=_MSG_GENERAL+1009,
	_MSG_EFFECT			=_MSG_GENERAL+1009,
	_MSG_PLAYERLEVELUP		=_MSG_GENERAL+1010,
	_MSG_PETLEVELUP		=_MSG_GENERAL+1011,
	_MSG_TURNEND			=_MSG_GENERAL+1012,
	_MSG_CHGPOINT			=_MSG_GENERAL+1013,
	_MSG_BATTLEEND			=_MSG_GENERAL+1014, 
	
	_MSG_TEAM				=_MSG_GENERAL+1020,
	_MSG_TEAMINFO			=_MSG_GENERAL+1021,
	//_MSG_GOODFRIEND		= _MSG_GENERAL+1022,
	
	_MSG_NOTIFY_CLIENT		= _MSG_GENERAL+1028,	
	
	
	_MSG_NPCINFO_LIST		= _MSG_GENERAL+1029,
	_MSG_NPCINFO			= _MSG_GENERAL+1030,
	_MSG_NPC				= _MSG_GENERAL+1031,
	_MSG_TASKBAR			= _MSG_GENERAL+1032,
	_MSG_TASKBARINFO		= _MSG_GENERAL+1033,
	_MSG_REMOTEATTACK		= _MSG_GENERAL+1034,
	_MSG_REMOTEATTACKINFO	= _MSG_GENERAL+1035,
	_MSG_PETKEEPER			= _MSG_GENERAL+1036,
	_MSG_COLOSSEUM			= _MSG_GENERAL+1037,
	_MSG_DUELCOMMAND		= _MSG_GENERAL+1038,
	_MSG_WRESTLER			= _MSG_GENERAL+1039,
	_MSG_ITEMKEEPER		= _MSG_GENERAL+1040,
	_MSG_TASKINFO			= _MSG_GENERAL+1041,
	_MSG_TASKCON			= _MSG_GENERAL+1042,
	_MSG_ITEM_COLLECTION	= _MSG_GENERAL+1043,
	_MSG_DOING_TASK_LIST	= _MSG_GENERAL+1044,
	_MSG_QUERY_TASK_LIST	= _MSG_GENERAL+1045,
	
	_MSG_BODICE			= _MSG_GENERAL+1050,
	_MSG_BOBET				= _MSG_GENERAL+1051,
	
	_MSG_SYNOPERATE		= _MSG_GENERAL+1052,
	_MSG_SYNCREATE			= _MSG_GENERAL+1053,
	_MSG_SYNUPDATE			= _MSG_GENERAL+1054,
	
	_MSG_CALLPET 			= _MSG_GENERAL+1056,
	_MSG_PETSHOP			= _MSG_GENERAL+1057,
	
	_MSG_CASINO			= _MSG_GENERAL+1058,
	_MSG_CASINOWHEEL		= _MSG_GENERAL+1059,
	_MSG_CASINOCARDS		= _MSG_GENERAL+1060,
	_MSG_CASINOMONEY		= _MSG_GENERAL+1061,
	
	//_MSG_EFFECT			= _MSG_GENERAL+1070,
	_MSG_QUIZGAME			= _MSG_GENERAL+1071,
	_MSG_PETMAGIC			= _MSG_GENERAL+1072,
	
	//_MSG_BOOTH         	    =_MSG_CALLPET,
	_MSG_BOOTH_BUSINESS	    =_MSG_GENERAL+1081,
	_MSG_BOOTH_BUS_INFO	    =_MSG_GENERAL+1082,
	_MSG_BOOTH_BUS_INVEST_INFO	=_MSG_GENERAL+1083,
	
	_MSG_MUSICACTION			= _MSG_GENERAL+1090,
	//HJQ <1091-------1291>
	_MSG_MUSICATTR				= _MSG_MUSICACTION+1,
	_MSG_KICK_OUT_TIP			= _MSG_GENERAL+1092,
	
	// 宠物操作
	_MSG_PET_ACTION				= _MSG_GENERAL+1094,
	// 查看宠物技能书
	_MSG_QUERY_PETCKILL			= _MSG_GENERAL+1095,
	
	//WQ<1292-------1491>
	_MSG_CREATE_SYN			= _MSG_GENERAL+1292,	// 建帮
	_MSG_SYN_QUERY				= _MSG_GENERAL+1293,	// 查询
	_MSG_SYN_ANNOUNCE			= _MSG_GENERAL+1294,	// 帮派公告
	_MSG_SYN_PANEL_INFO		= _MSG_GENERAL+1295,	// 帮派面板信息
	_MSG_SYN_TAXIS_INFO		= _MSG_GENERAL+1296,	// 帮派排行榜详细
	_MSG_SYN_INVITE			= _MSG_GENERAL+1297,	// 邀请入帮
	_MSG_INVITE_LIST				= _MSG_GENERAL+1298,	// 邀请列表
	_MSG_MBR_LIST				= _MSG_GENERAL+1299,	// 帮派成员列表
	_MSG_SYN_INFO				= _MSG_GENERAL+1300,	// 帮派基本信息
	_MSG_SYN_LIST				= _MSG_GENERAL+1301,	// 帮派排行榜
	_MSG_SYNDICATE				= _MSG_GENERAL+1302,
	_MSG_APPLY_LIST			= _MSG_GENERAL+1303,	// 申请列表
	_MSG_USER_LIST				= _MSG_GENERAL+1304,	// 玩家列表
	_MSG_QUERY_USER_LIST		= _MSG_GENERAL+1305,	// 查询玩家列表
	_MSG_USER_STATE			= _MSG_GENERAL+1306,	// 玩家特殊状态
	_MSG_EQUIP_BIND			= _MSG_GENERAL+1307,	// 装备绑定
	_MSG_USER_STATE_CHG		= _MSG_GENERAL+1308,	// 状态变化
	_MSG_MONSTER_LIST			= _MSG_GENERAL+1309,	// 精英怪信息
	_MSG_MONSTER_UPDATE		= _MSG_GENERAL+1310,	// 精英怪状态变化
	_MSG_TASK_ITEM_OPT			= _MSG_GENERAL+1311,	// 任务奖励物品选择列表
	_MSG_RMS_ITEM				= _MSG_GENERAL+1312,	// 客户端增量物品消息
	_MSG_CLIENT_BUG_REPORT		= _MSG_GENERAL+1313,	// 客户端bug报告消息
	_MSG_SYSTEM_DIALOG			= _MSG_GENERAL+1314,	// 系统对话框
	_MSG_BILLBOARD				= _MSG_GENERAL+1315,	// 排行榜列表
	_MSG_BILLBOARD_FIELD		= _MSG_GENERAL+1316,	// 排行榜字段信息
	_MSG_BILLBOARD_LIST		= _MSG_GENERAL+1317,	// 排行榜数据
	_MSG_BILLBOARD_QUERY		= _MSG_GENERAL+1318,	// 查询排行榜
	_MSG_BILLBOARD_USER		= _MSG_GENERAL+1319,	// 查询排行榜
	_MSG_NPC_STATUS			= _MSG_GENERAL+1320,	// 同步npc状态
	_MSG_QUERY_REG_SYN_LIST	= _MSG_GENERAL+1321,	// 下发应征军团列表
	_MSG_QUERY_DESC			= _MSG_GENERAL+1322,	// 查看描述
	
	//XWQ<1492-------1691>
	_MSG_AUCTION				= _MSG_GENERAL+1492,	// 拍卖
	_MSG_AUCTIONINFO			= _MSG_GENERAL+1493,	// 拍卖品信息
	_MSG_SHELVE				= _MSG_GENERAL+1494,	// 上架
	_MSG_BOOTH         	    = _MSG_GENERAL+1495,	// 摆摊
	_MSG_BOOTH_APPLY			= _MSG_GENERAL+1496,	// 摆摊申请
	_MSG_BOOTH_GOODS			= _MSG_GENERAL+1497,	// 摆摊物品信息
	_MSG_SEE					= _MSG_GENERAL+1498,	// 查看玩家信息，装备
	_MSG_EQUIP_INFO			= _MSG_GENERAL+1499,	// 装备信息
	_MSG_GOODFRIEND			= _MSG_GENERAL+1500,	// 好友
	_MSG_USERINFO_SEE			= _MSG_GENERAL+1501,	// 玩家信息(查看)
	//_MSG_LIFESKILL				= _MSG_GENERAL+1502,	// 生活技能
	_MSG_STONE					= _MSG_GENERAL+1503,	// 镶嵌挖除
	//_MSG_LIFESKILL_STUDY		= _MSG_GENERAL+1504,	// 学习配方或技能
	_MSG_SYNTHESIZE			= _MSG_GENERAL+1505,	// 合成物品
	_MSG_STONEINFO				= _MSG_GENERAL+1506,	// 镶嵌宝石信息
	_MSG_EQUIPIMPROVE			= _MSG_GENERAL+1507,	// 装备改良
	_MSG_LIMIT					= _MSG_GENERAL+1508,	// 背包仓库上限
	_MSG_AUCTION_QUEST			= _MSG_GENERAL+1509,	// 查询拍卖品信息
	_MSG_DIGOUT				= _MSG_GENERAL+1510,	// 宝石摘取
	_MSG_SHOPINFO				= _MSG_GENERAL+1511,	// 商品信息
	_MSG_REHEARSE				= _MSG_GENERAL+1512,	// 比武
	_MSG_CONTROLPOINT			= _MSG_GENERAL+1513,	// 控制点
	_MSG_AUCTION_QUEST_BY_NAME	= _MSG_GENERAL+1514,	// 拍卖按名字查询
	_MSG_GIFT					= _MSG_GENERAL+1515,	// 发放礼物
	_MSG_EQUIP_EFFECT			= _MSG_GENERAL+1516,	// 装备是否失效
	_MSG_TIDY_UP_BAG			= _MSG_GENERAL+1517,	// 整理背包
	_MSG_SPLIT_ITEM			= _MSG_GENERAL+1518,	// 拆分物品
	_MSG_TUTOR					= _MSG_GENERAL+1519,	// 导师
	_MSG_TUTOR_INFO			= _MSG_GENERAL+1520,	// 导师信息
	_MSG_COMPLETE_TASK			= _MSG_GENERAL+1521,	// 完成任务
	_MSG_REG_TUTOR_INFO		= _MSG_GENERAL+1522,	// 注册导师信息
	_MSG_USER_POS				= _MSG_GENERAL+1523,	// 玩家位置
	_MSG_REPUTE_ATTR			= _MSG_GENERAL+1524,	// 单个声望值
	_MSG_COLLECTION			= _MSG_GENERAL+1525,	// 采集
	_MSG_FORMULA				= _MSG_GENERAL+1526,	// 配方
	_MSG_MAGIC_GOODS			= _MSG_GENERAL+1527,	// 技能商店信息
	_MSG_TIP					= _MSG_GENERAL+1528,	// 切屏提示消息，小贴士
	_MSG_CONTRIBUTE			= _MSG_GENERAL+1529,	// 捐献
	_MSG_CAMP_STORAGE			= _MSG_GENERAL+1530,	// 阵营仓库
	_MSG_MONSTER_INFO_LIST		= _MSG_GENERAL+1531,	// 怪物信息
	_MSG_NPC_POSITION			= _MSG_GENERAL+1532,	// NPC位置
	_MSG_NPC_TALK				= _MSG_GENERAL+1533,	// NPC说话
	_MSG_BATTLE_SKILL_LIST		= _MSG_GENERAL+1534,	// 战斗时下发可用技能列表
	_MSG_ITEM_TYPE_INFO		= _MSG_GENERAL+1535,	// itemtype信息
	_MSG_RESET_POSITION		= _MSG_GENERAL+1536,	// 卡死复位
	_MSG_GM_MAIL				= _MSG_GENERAL+1537,	// 玩家提问
	_MSG_CUSTOMER_SERVICE		= _MSG_GENERAL+1538,	// 客服声明
	_MSG_RECHARGE				= _MSG_GENERAL+1539,	// 充值
	_MSG_RECHARGE_RETURN		= _MSG_GENERAL+1540,	// 充值回馈
	_MSG_CHG_MAP_FAIL			= _MSG_GENERAL+1541,	// 切屏失败
	_MSG_COMPETITION			= _MSG_GENERAL+1542,	// 比赛
	_MSG_ENTER_ARENA			= _MSG_GENERAL+1543,	// 进入比武场
	_MSG_WISH					= _MSG_GENERAL+1544,	// 许愿
	_MSG_SHOP_CENTER			= _MSG_GENERAL+1545,	// 商城
	_MSG_WALK_TO				= _MSG_GENERAL+1546,
	_MSG_COMMON_LIST			= _MSG_GENERAL+1547,
	_MSG_COMMON_LIST_RECORD	= _MSG_GENERAL+1548,
	_MSG_LIGHT_EFFECT			= _MSG_GENERAL+1549,
	_MSG_CHG_PET_POINT			= _MSG_GENERAL+1550,
	_MSG_PET_SKILL				= _MSG_GENERAL+1551,	// 宠物技能
	_MSG_EQUIP_SET_CFG			= _MSG_GENERAL+1552,
	_MSG_POS_TEXT				= _MSG_GENERAL+1564,
	_MSG_SYN_LIST_EX			= _MSG_GENERAL+1565,
	_MSG_INVITE_LIST_EX			= _MSG_GENERAL+1566,	// 新邀请消息
	_MSG_SYN_DONATE			= _MSG_GENERAL+1568,
	_MSG_CHARGE_GIFT_INFO		= _MSG_GENERAL+1569,
	
	//XB<1692-------1891>
	_MSG_REPUTE				= _MSG_GENERAL+1692,	// 声望
	_MSG_QUERY_HONOR_LIST		= _MSG_GENERAL+1693,	// 查询荣誉排名表
	_MSG_HONOR_LIST			= _MSG_GENERAL+1694,	// 返回荣誉排名表
	
	/** 村落列表信息 */
	_MSG_HAMLET = _MSG_GENERAL + 1555,
	/** 进入村落或村庄 */
	_MSG_ENTER_HAMLET = _MSG_GENERAL + 1556,
	/** 村落或村庄的实体列表 */
	_MSG_FARM_LIST = _MSG_GENERAL + 1557,
	/**庄园仓库信息*/
	_MSG_FARM_STORAGE = _MSG_GENERAL+1558,
	/**庄园仓库存取*/
	_MSG_STORAGE_ACCESS=_MSG_GENERAL+1559,
	/** 农作物操作 */
	_MSG_FARM_PRODUCE = _MSG_GENERAL + 1560,
	/** 庄园动态 */
	_MSG_FARM_TRENDS = _MSG_GENERAL + 1561,
	
	/** 收获成功 */
	_MSG_HARVEST= _MSG_GENERAL + 1323,
	/** 计时信息 */
	_MSG_FARM_TIME_COUNT = _MSG_GENERAL + 1324,
	/** 留言列表*/
	_MSG_FARM_MESSAGE_LIST = _MSG_GENERAL + 1325,
	/** 留言查询，删除，翻页*/
	_MSG_FARM_QUERY_MESSAGE = _MSG_GENERAL + 1326,
	/** 留言发表*/
	_MSG_FARM_LEAVE_MESSAGE = _MSG_GENERAL + 1327,
	/** 牧场操作选项*/
	_MSG_FARM_MU_CHANG_OPT = _MSG_GENERAL + 1328,
	/** 牧场操作提交*/
	_MSG_FARM_MU_CHANG = _MSG_GENERAL + 1329,
	/** 牧场作物*/
	_MSG_FARM_MU_CHANG_PROD_OPT = _MSG_GENERAL + 1330,
	
	/** 设置庄园文字;	 */
	_MSG_SET_FARM_INFO	= _MSG_GENERAL+1332,	// 设置庄园文字;	
	/** 设置庄园建筑名字*/
	_MSG_SET_FARM_ENTITY_NAME = _MSG_GENERAL+1333,	// 设置庄园建筑名字;		
	/**更新庄园动态*/
	_MSG_UPDATE_FARM_TRENDS = _MSG_GENERAL+1336,
	/**更新地图名字*/
	_MSG_UPDATE_MAP_NAME = _MSG_GENERAL+1337,	
	/** 庄园迁移 */
	_MSG_MOVE_FARMLAND = _MSG_GENERAL+1334,	// 庄园迁移;	
	/** 庄园迁移NPC */
	_MSG_MOVE_FARMLAND_NPC_LIST= _MSG_GENERAL+1335,	// 庄园迁移NPC;	
	/** 活动列表 */
	_MSG_ACTIVITY = _MSG_GENERAL + 1331,
	/*切屏点*/
	_MSG_PORTAL = _MSG_GENERAL + 1562,
	/**可接任务列表*/
	_MSG_QUERY_TASK_LIST_EX = _MSG_GENERAL + 1563,
	//
	
	/**查询社交信息*/
	_MSG_QUERY_SOCIAL_INFO = _MSG_GENERAL + 1567,
	
	/**请求进入寻宝状态*/
	_MSG_TRY_BEGIN_TREASURE_HUNT = 3000,
	
	/**显示寻宝奖励结算信息*/
	_MSG_SHOW_TREASURE_HUNT_AWARD = 3001,
	
	/**请求寻宝的机率信息*/
	_MSG_QUERY_TREASURE_HUNT_PROB = 3002,
	
	/**返回寻宝的机率信息*/
	_MSG_RESPOND_TREASURE_HUNT_PR0B = 3003,
	
	/**请求关于寻宝说明的文字信息*/
	_MSG_QUERY_TREASURE_HUNT_INFO = 3004,
	
	/**返回寻宝说明的文字信息*/
	_MSG_RESPOND_TREASURE_HUNT_INFO = 3005,
	
	/**战场商城商品信息*/
	_MSG_SHOP_BATTLE = 3006,
	
	/**战场商城商品分类*/
	_MSG_SHOP_BATTLE_GOODS_TYPE = 3007,
	
	/**系统商城商品分类*/
	_MSG_SHOP_CENTER_GOODS_TYPE = 3008,
	
	/**可用战场的列表*/
	_MSG_BATTLEFIELD_LIST = 3020,
	
	/**战场状态报名信息*/
	_MSG_BATTLEFIELD_SIGNUP = 3009,
	
	/**战场状态报名更新信息*/
	_MSG_BATTLEFIELD_UPDATE_SIGNIN = 3011,
	
	/**战场背景介绍*/
	_MSG_BATTLEFIELD_INTRO = 3010,
	
	/**战场报名*/
	_MSG_BATTLEFIELD_SIGNIN = 3012,
	
	/**战场死亡后复活*/
	_MSG_BATTLEFIELD_RELIVE = 3018,
	
	/**战场确认*/
	_MSG_BATTLEFIELD_CONFIRM = 3013,
	
	/**购买物品并使用*/
	_MSG_BUY_GOODS_AUTO_USE = 3030,
	/**开启新的技能槽*/
	_MSG_OPEN_SKILL_SLOT = 3031,
	/**配置技能槽位*/
	_MSG_CONFIG_SKILL_SLOT = 3032,
	/**回购卖出物品*/
	_MSG_BUYBACK_ACTION		= 3033,
	
	_MSG_GAME_QUIT			= 0xfffe,
	
	//BOSS战排行信息
	_MSG_BOSS_BATTLE_INFO	=4007,
	
	//路障信息
	_MSG_ROADBLOCK	=4008,
	
	//BOSS战自身信息
	_MSG_BOSS_BATTLE_SELF	=4009,
	
	//战斗回放结果信息
	_MSG_BATTLE_RECORD_END	=4011,
	
	//打开宝箱信息
	_MSG_INSTANCING_BOX_AWARD_LIST	=4573,
	
	//////////////////////////////////////////////////////////////////////////
	//////////////////////////////////////////////////////////////////////////
	_MSG_AUTHORIZE			=_MSG_CONNECT,
	_MSG_FLOWER			=_MSG_POSITION,
	_MSG_STORAGE			=_MSG_ITEMKEEPER,
	_MSG_TITLE			    =_MSG_NPC,
	
	//////////////////////////////////////////////////////////////////////////
	//ITEST
	MB_ITEST_BEGIN							= 10000,
	MB_ITEST_EXCHANG_KEY						= 10001, //交换加密KEY
	MB_ITEST_PRINT_LOG						= 10100, //启动和关闭调试日志输出
	MB_ITEST_END								= 10199,	
	//ITEST
	////////////////////////////////////////////////////////////////////////////////////////
	//LOGINSYSTEM
	MB_LOGINSYSTEM_BEGIN						= 59999,
	MB_LOGINSYSTEM_MOBILE_SERVER_NOTIFY		= 60000, //MobileServer 消息通知
	MB_LOGINSYSTEM_EXCHANG_KEY				= 60001, //客户端发送   当前版本号、手机的加密KEY；服务器返回   MobileServer的加密KEY
	MB_LOGINSYSTEM_LOGIN_GAME_SERVER			= 60002, //客户端发送   用户名 、密码、游戏服务器的名字
	MB_LOGINSYSTEM_SENDBACK_APPSERVERINFO		= 60003, //服务器返回   应用服务器的IP地址、端口号、用户的帐号ID、KeyCode 
	MB_LOGINSYSTEM_BEAT_HEART					= 60006, //客户端发送心跳包
	_MSG_RECORD_CHANNEL			= 60007, //渠道信息登记
	_MSG_VERSION					= 60008, //版本验证
	_MSG_MPF_VERSION				= 60009, //新版本验证
	MB_LOGINSYSTEM_CREATE_NEWBIE				= 60018, //通知服务器创建玩家新角色				
	MB_LOGINSYSTEM_END						= 60199,
	//LOGINSYSTEM
	//
	MB_MSG_RECHARGE							= 60201, //充值
	MB_MSG_RECHARGE_RETURN					= 60202, //充值回馈
	MB_MSG_CHANGE_PASS						= 60203, //修改密码
	MB_MSG_ACCOUNT_NAME						= 60204, //帐号名
	//
	////////////////////////////////////////////////////////////////////////////////////////
	//TALKSYSTEM
	MB_TALKSYSTEM_BEGIN 						= 20001,
	MB_TALKSYSTEM_TALK						= MB_TALKSYSTEM_BEGIN, //聊天
	MB_TALKSYSTEM_END							= MB_TALKSYSTEM_BEGIN,
	//TALKSYSTEM
	////////////////////////////////////////////////////////////////////////////////////////
	//MAPMGR
	MB_MAPMGR_BEGIN 							= 60400,
	MB_MAPMGR_END								= 60599,
	//TALKSYSTEM
	////////////////////////////////////////////////////////////////////////////////////////
	MB_MSG_MAX_ID							= 65535,
	MB_MSG_DISAPPEAR						= 1200,//玩家从地图上消失
	MB_LOGINSYSTEM_NORSA_EXCHANGE_KEY		= 60088,
	MB_SERVER_INFO_REQUEST			= 60098,
	/**上传用户名与机型信息*/
	_MSG_ACCOUNT_MOBILE=60198,
	// -------------------- change site code msg type define --------------------------
	_MSG_SITE_CODE		    =9000,
	/**密保*/
	MB_MSG_MOBILE_PWD=60205, // 手机绑定、密码找回
};

#endif // _ND_MSG_DEFINE_H_/** 荣誉和声望值 */
